#baseURL: "https://swimmingliu.netlify.app/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://swimmingliu.cn/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: SwimmingLiu's Blog 
pagination.pagerSize: "5"
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: 🏡 Home
                  url: index.html
                  weight: 5
                - name: 🔍 Search
                  url: search/
                  weight: 8
                - name: 👨🏻‍🎓 About Me
                  url: https://avely.me/swimmingliu
                  weight: 15
                - name: 🗒️ Posts
                  url: posts/
                  weight: 10  
                - name: 📃 Archive
                  url: archives/
                  weight: 12
                - name: 📑 Tags
                  url: tags/
                  weight: 13



outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    #description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: 👨🏻‍🎓 SwimmingLiu 

    defaultTheme: PaperMod
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    comments: true
    images: ["papermod-cover.png"]

    profileMode:
        enabled: true
        title: 𝓢𝔀𝓲𝓶𝓶𝓲𝓷𝓰𝓛𝓲𝓾'𝓼 𝓑𝓵𝓸𝓰
        imageUrl: https://oss.swimmingliu.cn/SwimmingLiu-08f19bdf2935.png
        imageTitle: 𝓢𝔀𝓲𝓶𝓶𝓲𝓷𝓰𝓛𝓲𝓾
        imageWidth: 200
        imageHeight: 200
        buttons:
            - name: 📝 Paper Notes
              url: posts/papernotes
            - name: 📓 Diary
              url: posts/diary
            - name: 💻 Job
              url: posts/job


    socialIcons:
        - name: github
          url: "https://github.com/SwimmingLiu"
        - name: Instagram
          url: "https://www.instagram.com/thatswimming/"
        - name: Bilibili
          url: https://space.bilibili.com/156805097
        - name: email
          url: "mailto:SwimmingLiu@outlook.com"
        - name: tiktok
          url: "https://v.douyin.com/iRABBfeY"


    label:
        text: "𝓢𝔀𝓲𝓶𝓶𝓲𝓷𝓰𝓛𝓲𝓾'𝓼 𝓑𝓵𝓸𝓰"
        icon: https://oss.swimmingliu.cn/swimmingliu_icon-7772456ede34.jpg
        iconHeight: 30

    assets:
        disableHLJS: true
        favicon: https://oss.swimmingliu.cn/swimmingliu_icon-7772456ede34.jpg
        favicon16x16: https://oss.swimmingliu.cn/swimmingliu_icon-7772456ede34.jpg
        favicon32x32: https://oss.swimmingliu.cn/swimmingliu_icon-7772456ede34.jpg
        apple_touch_icon: https://oss.swimmingliu.cn/swimmingliu_icon-7772456ede34.jpg
        safari_pinned_tab: https://oss.swimmingliu.cn/swimmingliu_icon-7772456ede34.jpg
    
    StartYear: 2023 # 底部开始年份
    FilingNo: 浙ICP备2024056260号 # 底部备案号

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
